version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cctv_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cctv_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - cctv_network

  backend:
    build: .
    container_name: cctv_backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: cctv_system
      SERVER_PORT: 5009
      UPLOAD_DIR: /app/uploads
    ports:
      - "5009:5009"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - cctv_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: cctv_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - backend
    networks:
      - cctv_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cctv_network:
    driver: bridge