# Removed obsolete version field

services:
  postgres:
    image: postgres:15-alpine
    container_name: cctv_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Make schema.sql optional if it doesn't exist
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - cctv_network
    restart: unless-stopped
    # Fix health check for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build: ./backend
    container_name: backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      SERVER_PORT: ${SERVER_PORT}
      UPLOAD_DIR: ${UPLOAD_DIR}
      TZ: ${TZ}
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "5009:5009"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - cctv_network
    restart: unless-stopped
    # Add delay and retry logic for database connection

  nginx:
    image: nginx:alpine
    container_name: cctv_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/uploads:/var/www/uploads:ro
    depends_on:
      - backend
    networks:
      - cctv_network
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: cctv_adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - cctv_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  cctv_network:
    driver: bridge